FROM nginx:latest

COPY docker/nginx.conf /etc/nginx/conf.d/default.conf

WORKDIR /var/www/laravel_app

# Copy application code
COPY ./ /var/www/laravel_app

# Set permissions for Laravel
RUN chown -R www-data:www-data /var/www/laravel_app \
    && chmod -R 755 /var/www/laravel_app/storage /var/www/laravel_app/bootstrap/cache /var/www/laravel_app/public
