FROM node:22

WORKDIR /var/www/laravel_app

# Copy hanya file yang diperlukan untuk instalasi dependensi
COPY package.json pnpm-lock.yaml* ./

# Install dependensi menggunakan PNPM
RUN npm install

# Jalankan perintah default
CMD ["npm", "run", "dev"]
# CMD ["pnpm", "run", "build"]
